"""Markdown report generation for ThreatLens scan results."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from threatlens import __version__
from threatlens.models import Alert, Severity

_SEVERITY_ICON = {
    Severity.CRITICAL: "[CRIT]",
    Severity.HIGH: "[HIGH]",
    Severity.MEDIUM: "[MED]",
    Severity.LOW: "[LOW]",
}

_SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
}


def _escape(text: str) -> str:
    """Escape pipe and backslash characters for use inside Markdown tables."""
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def export_markdown(
    alerts: list[Alert],
    output_path: Path,
    total_events: int,
    elapsed: float = 0.0,
) -> None:
    """Export alerts to a Markdown report file."""
    counts = {s: 0 for s in Severity}
    for a in alerts:
        counts[a.severity] += 1

    lines: list[str] = []
    lines.append("# ThreatLens Report\n")
    lines.append(
        f"Generated by ThreatLens v{__version__} on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    )

    lines.append("## Summary\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Events analyzed | {total_events:,} |")
    lines.append(f"| Alerts generated | {len(alerts)} |")
    lines.append(f"| Scan duration | {elapsed:.2f}s |")
    lines.append(f"| Critical | {counts[Severity.CRITICAL]} |")
    lines.append(f"| High | {counts[Severity.HIGH]} |")
    lines.append(f"| Medium | {counts[Severity.MEDIUM]} |")
    lines.append(f"| Low | {counts[Severity.LOW]} |\n")

    if not alerts:
        lines.append("## Alerts\n")
        lines.append("No threats detected. Clean scan.\n")
        output_path.write_text("\n".join(lines), encoding="utf-8")
        return

    sorted_alerts = sorted(alerts, key=lambda a: _SEVERITY_ORDER.get(a.severity, 99))

    lines.append(f"## Alerts ({len(alerts)})\n")
    lines.append("| Severity | Rule | Timestamp | MITRE | Description |")
    lines.append("|---|---|---|---|---|")
    for a in sorted_alerts:
        sev = _SEVERITY_ICON.get(a.severity, a.severity.value.upper())
        mitre = (
            f"{a.mitre_tactic} / {a.mitre_technique}"
            if a.mitre_technique
            else ""
        )
        lines.append(
            f"| {sev} | {_escape(a.rule_name)} | {a.timestamp_str} "
            f"| {_escape(mitre)} | {_escape(a.description)} |"
        )

    lines.append("\n## Alert Detail\n")
    for i, a in enumerate(sorted_alerts, 1):
        sev = _SEVERITY_ICON.get(a.severity, a.severity.value.upper())
        lines.append(f"### {i}. {sev} {a.rule_name}\n")
        lines.append(f"- **Timestamp:** {a.timestamp_str}")
        lines.append(f"- **Description:** {a.description}")
        if a.mitre_technique:
            lines.append(f"- **MITRE:** {a.mitre_tactic} / {a.mitre_technique}")
        if a.recommendation:
            lines.append(f"- **Recommendation:** {a.recommendation}")
        if a.evidence:
            lines.append(f"- **Evidence ({len(a.evidence)} items):**")
            for ev in a.evidence[:5]:
                pairs = ", ".join(f"`{k}`={v}" for k, v in ev.items())
                lines.append(f"    - {pairs}")
            if len(a.evidence) > 5:
                lines.append(f"    - ... ({len(a.evidence) - 5} more)")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
