"""MITRE ATT&CK Navigator layer export for ThreatLens.

Produces a Navigator v4.5 JSON layer that can be loaded at
https://mitre-attack.github.io/attack-navigator/ to visualize which
techniques fired during a scan and how often. Each technique gets a
score equal to the number of alerts that referenced it, a colour from
the layer's gradient, and a comment listing the contributing rule names.

Spec: https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4_5.md
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

from threatlens.models import Alert

_TECHNIQUE_RE = re.compile(r"T\d{4}(?:\.\d{3})?")


def _technique_ids(alert: Alert) -> list[str]:
    """Extract MITRE technique IDs from an alert's MITRE fields."""
    blob = f"{alert.mitre_technique} {alert.mitre_tactic}"
    return _TECHNIQUE_RE.findall(blob)


def build_navigator_layer(
    alerts: list[Alert],
    layer_name: str = "ThreatLens Scan",
    description: str | None = None,
) -> dict[str, Any]:
    """Build an ATT&CK Navigator v4.5 layer dict from a list of alerts."""
    by_tech: dict[str, list[Alert]] = defaultdict(list)
    for alert in alerts:
        for tid in _technique_ids(alert):
            by_tech[tid].append(alert)

    techniques = []
    max_score = max((len(v) for v in by_tech.values()), default=1)

    for tid, hits in sorted(by_tech.items()):
        rule_names = sorted({a.rule_name for a in hits})
        severities = sorted({str(a.severity) for a in hits})
        techniques.append({
            "techniqueID": tid,
            "score": len(hits),
            "color": "",
            "comment": (
                f"{len(hits)} alert(s) across "
                f"{len(rule_names)} rule(s): {', '.join(rule_names[:5])}"
                + (" ..." if len(rule_names) > 5 else "")
                + f". Severities: {', '.join(severities)}."
            ),
            "enabled": True,
            "metadata": [
                {"name": "alerts", "value": str(len(hits))},
                {"name": "rules", "value": ", ".join(rule_names[:10])},
            ],
            "showSubtechniques": "." in tid,
        })

    layer = {
        "name": layer_name,
        "versions": {
            "attack": "14",
            "navigator": "4.9.1",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": description or (
            f"Generated by ThreatLens on {datetime.now().isoformat()} "
            f"covering {len(alerts)} alerts across {len(by_tech)} techniques."
        ),
        "filters": {"platforms": ["Windows", "Linux", "macOS"]},
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": True,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffe082", "#ff5252"],
            "minValue": 0,
            "maxValue": max(max_score, 1),
        },
        "legendItems": [
            {"label": "Detected by ThreatLens", "color": "#ff5252"},
        ],
        "metadata": [
            {"name": "tool", "value": "threatlens"},
            {"name": "alerts", "value": str(len(alerts))},
        ],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }
    return layer


def export_navigator_layer(
    alerts: list[Alert],
    output_path: Path,
    layer_name: str = "ThreatLens Scan",
    description: str | None = None,
) -> None:
    """Write an ATT&CK Navigator layer JSON to disk."""
    layer = build_navigator_layer(alerts, layer_name=layer_name, description=description)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(layer, indent=2), encoding="utf-8")
